const TEAM_NAMES_KO = Object.freeze({
  AFG: "아프가니스탄",
  ALB: "알바니아",
  ALG: "알제리",
  AND: "안도라",
  ANG: "앙골라",
  ANT: "앤티가 바부다",
  ARG: "아르헨티나",
  ARM: "아르메니아",
  ARU: "아루바",
  AUS: "호주",
  AUT: "오스트리아",
  AZE: "아제르바이잔",
  BAH: "바하마",
  BAN: "방글라데시",
  BAR: "바베이도스",
  BDI: "부룬디",
  BEL: "벨기에",
  BER: "버뮤다",
  BHU: "부탄",
  BIH: "보스니아 헤르체고비나",
  BIZ: "벨리즈",
  BLR: "벨라루스",
  BOL: "볼리비아",
  BOT: "보츠와나",
  BRA: "브라질",
  BRN: "바레인",
  BRU: "브루나이",
  BUL: "불가리아",
  BUR: "부르키나파소",
  CAF: "중앙아프리카공화국",
  CAM: "캄보디아",
  CAN: "캐나다",
  CAY: "케이맨 제도",
  CHA: "차드",
  CHI: "칠레",
  CHN: "중국",
  CIV: "코트디부아르",
  CMR: "카메룬",
  COD: "콩고민주공화국",
  COL: "콜롬비아",
  COM: "코모로",
  CPV: "카보베르데",
  CRC: "코스타리카",
  CRO: "크로아티아",
  CUB: "쿠바",
  CUR: "퀴라소",
  CYP: "키프로스",
  CZE: "체코",
  DEN: "덴마크",
  DJI: "지부티",
  DMA: "도미니카",
  DOM: "도미니카 공화국",
  ECU: "에콰도르",
  EGY: "이집트",
  ENG: "잉글랜드",
  ESA: "엘살바도르",
  ESP: "스페인",
  EST: "에스토니아",
  ETH: "에티오피아",
  FAI: "페로 제도",
  FIJ: "피지",
  FIN: "핀란드",
  FRA: "프랑스",
  GAB: "가봉",
  GAM: "감비아",
  GCI: "건지",
  GEO: "조지아",
  GEQ: "적도 기니",
  GER: "독일",
  GHA: "가나",
  GRE: "그리스",
  GRL: "그린란드",
  GRN: "그레나다",
  GUA: "과테말라",
  GUI: "기니",
  GUM: "괌",
  GUY: "가이아나",
  HAI: "아이티",
  HKG: "홍콩",
  HON: "온두라스",
  HUN: "헝가리",
  INA: "인도네시아",
  IND: "인도",
  IOM: "맨섬",
  IRI: "이란",
  IRL: "아일랜드",
  IRQ: "이라크",
  ISL: "아이슬란드",
  ISR: "이스라엘",
  ISV: "미국령 버진아일랜드",
  ITA: "이탈리아",
  IVB: "영국령 버진아일랜드",
  JAM: "자메이카",
  JCI: "저지",
  JOR: "요르단",
  JPN: "일본",
  KAZ: "카자흐스탄",
  KEN: "케냐",
  KGZ: "키르기스스탄",
  KIR: "키리바시",
  KOR: "대한민국",
  KOS: "코소보 *",
  KSA: "사우디아라비아",
  KUW: "쿠웨이트",
  LAO: "라오스",
  LAT: "라트비아",
  LBA: "리비아",
  LBN: "레바논",
  LBR: "라이베리아",
  LCA: "세인트루시아",
  LES: "레소토",
  LIE: "리히텐슈타인",
  LTU: "리투아니아",
  LUX: "룩셈부르크",
  MAC: "마카오",
  MAD: "마다가스카르",
  MAR: "모로코",
  MAS: "말레이시아",
  MAW: "말라위",
  MDA: "몰도바",
  MDV: "몰디브",
  MEX: "멕시코",
  MGL: "몽골",
  MHL: "마셜 제도",
  MKD: "북마케도니아",
  MLI: "말리",
  MLT: "몰타",
  MNC: "모나코",
  MNE: "몬테네그로",
  MOZ: "모잠비크",
  MRI: "모리셔스",
  MTN: "모리타니",
  MYA: "미얀마",
  NAM: "나미비아",
  NCA: "니카라과",
  NCL: "뉴칼레도니아",
  NED: "네덜란드",
  NEP: "네팔",
  NGR: "나이지리아",
  NIG: "니제르",
  NOR: "노르웨이",
  NRU: "나우루",
  NZL: "뉴질랜드",
  OMA: "오만",
  PAK: "파키스탄",
  PAN: "파나마",
  PAR: "파라과이",
  PER: "페루",
  PHI: "필리핀",
  PLE: "팔레스타인",
  PLW: "팔라우",
  PNG: "파푸아뉴기니",
  POL: "폴란드",
  POR: "포르투갈",
  PUR: "푸에르토리코",
  QAT: "카타르",
  ROU: "루마니아",
  RSA: "남아프리카공화국",
  SCO: "스코틀랜드",
  SEN: "세네갈",
  SEY: "세이셸",
  SGP: "싱가포르",
  SKN: "세인트키츠 네비스",
  SLE: "시에라리온",
  SLO: "슬로베니아",
  SMR: "산마리노",
  SOL: "솔로몬 제도",
  SOM: "소말리아",
  SRB: "세르비아",
  SRI: "스리랑카",
  SSD: "남수단",
  STP: "상투메 프린시페",
  SUD: "수단",
  SUI: "스위스",
  SUR: "수리남",
  SVK: "슬로바키아",
  SWE: "스웨덴",
  SWZ: "에스와티니",
  SYR: "시리아",
  TAN: "탄자니아",
  TGA: "통가",
  THA: "태국",
  TJK: "타지키스탄",
  TKM: "투르크메니스탄",
  TLS: "동티모르",
  TOG: "토고",
  TPE: "차이니스 타이베이",
  TTO: "트리니다드 토바고",
  TUN: "튀니지",
  TUR: "튀르키예",
  UAE: "아랍에미리트",
  UGA: "우간다",
  UKR: "우크라이나",
  URU: "우루과이",
  USA: "미국",
  UZB: "우즈베키스탄",
  VAN: "바누아투",
  VEN: "베네수엘라",
  VIE: "베트남",
  VIN: "세인트빈센트 그레나딘",
  WLS: "웨일스",
  YEM: "예멘",
  ZAM: "잠비아",
  ZIM: "짐바브웨",
});

function getTeamDisplayName(team, language) {
  if (language !== "ko") {
    return team.name;
  }

  const localizedName =
    TEAM_NAMES_KO[team.federation] ?? team.name;

  const numberedTeamMatch =
    team.name.match(/\s+(\d+)$/);

  if (!numberedTeamMatch) {
    return localizedName;
  }

  return `${localizedName} ${numberedTeamMatch[1]}`;
}

window.TeamNames = Object.freeze({
  getDisplayName: getTeamDisplayName,
});